name: Wake up Bot on Glitch

on:
  schedule:
    - cron: '0/2 * * * *'

jobs:
  materials:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x, 12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Wake up bot
        run: node src/glitch/wakup.js
