name: Wake up Bot on Glitch

on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  wakup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x, 12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Wake up bot
        run: |
          npm ci
          node src/glitch/wakup.js
